application:
  config:
    description: Profile Testing

server:
  port: 9082

spring:
  application:
    name: service-customer
  cloud:
    config:
      profile: qa

  data:
    mongodb:
      database: 'customerdb'
      host: 'localhost'
      port: 27017