application:
  config:
    description: Profile Default

server:
  port: 8083

spring:
  application:
    name: service-account
  cloud:
    config:
      profile: dev

  data:
    mongodb:
      database: 'accountdb'
      host: 'localhost'
      port: 27017

#Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka
    #enabled: false

#Endpoints
config:
  base:
    customer:
      endpoint: 'http://localhost:8082/api/v1/customer'
    account:
      endpoint: http://localhost:8083/api/v1/account
    credit:
      endpoint: http://localhost:8084/api/v1/credit

#Endpoints Eureka URL
config-eureka:
  base:
    customer:
      endpoint: 'http://service-customer/api/v1/customer'
    account:
      endpoint: 'http://service-account/api/v1/account'
    credit:
      endpoint: 'http://service-credit/api/v1/credit'