application:
  config:
    description: Profile Production

server:
  port: 10083

spring:
  application:
    name: service-account
  cloud:
    config:
      profile: dev

  data:
    mongodb:
      database: 'accountdb'
      host: 'localhost'
      port: 27017

#Endpoints
config:
  base:
    customer:
      endpoint: 'http://localhost:8082/customerType/1'