application:
  config:
    description: Profile Default

server:
  port: 8084

spring:
  application:
    name: service-credit
  cloud:
    config:
      profile: dev

  data:
    mongodb:
      database: 'creditdb'
      host: 'localhost'
      port: 27017